name: iov_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localization: ^0.2.3
  jwt_decoder: ^2.0.1
  device_info_plus: ^9.0.2
  firebase_core: ^2.9.0
  firebase_messaging: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  http: ^1.2.2
  shared_preferences: ^2.3.3


flutter:
  assets:
    - .env
    - assets/logo.png
    - assets/lang/en.json
    - assets/lang/vi.json
  uses-material-design: true


